services:
  # A Redis instance for our Celery queue
  - type: redis
    name: redis-mdraft
    plan: free
    ipAllowList: [] # Allow all, or specify IPs if needed
    maxmemoryPolicy: allkeys-lru

  # The main Flask web application
  - type: web
    name: mdraft-web
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    buildCommand: pip install -r requirements-web.txt
    startCommand: flask db upgrade && gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

  # The Celery background worker
  - type: worker
    name: mdraft-worker
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    buildCommand: pip install -r requirements-worker.txt
    startCommand: celery -A celery_worker.celery worker --loglevel=info --pool=threads --concurrency=4 --without-gossip --without-mingle
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

  # Cron job for expiring trials
  - type: cron
    name: expire-trials
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery call app.tasks.expire_trials
    schedule: "0 0 * * *"  # Daily at midnight UTC
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

  # Cron job for resetting monthly usage
  - type: cron
    name: reset-monthly-usage
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery call app.tasks.reset_monthly_usage
    schedule: "0 0 1 * *"  # First day of every month at midnight UTC
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

  # Cron job for Redis health check (keeps Redis active)
  - type: cron
    name: redis-health-check
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery call app.tasks.redis_health_check
    schedule: "*/30 * * * *"  # Every 30 minutes
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

envVarGroups:
  - name: mdraft-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure secret key
      - key: GCS_BUCKET_NAME
        value: mdraft-uploads-1974 # <-- PASTE YOUR BUCKET NAME
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcs-credentials.json # Path on Render's server
      - key: DOCAI_PROCESSOR_ID
        value: mdraft-processor # <-- PASTE YOUR PROCESSOR ID