services:
  # A Redis instance for our Celery queue
  - type: redis
    name: redis-mdraft
    plan: free
    ipAllowList: [] # Allow all, or specify IPs if needed
    maxmemoryPolicy: allkeys-lru

  # The main Flask web application
  - type: web
    name: mdraft-web
    env: python
    plan: free
    # CACHE BUST: Multiple strategies to force fresh build
    buildCommand: "pip install --no-cache-dir --force-reinstall -r requirements.txt && echo 'BUILD-v7-STRIPE-FIX-$(date +%s)'"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

  # The Celery background worker with FORCED REBUILD
  - type: worker
    name: mdraft-worker
    env: python
    plan: free
    # CACHE BUST: Force fresh dependency install with different timestamp
    buildCommand: "pip install --no-cache-dir --force-reinstall -r requirements.txt && echo 'WORKER-BUILD-v7-STRIPE-FIX-$(date +%s)'"
    startCommand: "celery -A celery_worker.celery worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: run.py
      - key: FLASK_CONFIG
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: redis-mdraft
          property: connectionString
      - fromGroup: mdraft-secrets

envVarGroups:
  - name: mdraft-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure secret key
      - key: GCS_BUCKET_NAME
        value: mdraft-uploads-1974 # <-- PASTE YOUR BUCKET NAME
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcs-credentials.json # Path on Render's server
      - key: DOCAI_PROCESSOR_ID
        value: mdraft-processor # <-- PASTE YOUR PROCESSOR ID