"""Add trial and usage tracking fields

Revision ID: 2650ead023bc
Revises: 356d23396c69
Create Date: 2025-07-24 12:56:54.483355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2650ead023bc'
down_revision = '356d23396c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages_processed', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('on_trial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pro_pages_processed_current_month', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_provider_user_id'))
        batch_op.drop_column('provider')
        batch_op.drop_column('provider_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_user_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_provider_user_id'), ['provider_user_id'], unique=False)
        batch_op.drop_column('pro_pages_processed_current_month')
        batch_op.drop_column('on_trial')
        batch_op.drop_column('trial_end_date')
        batch_op.drop_column('trial_start_date')

    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_column('pages_processed')

    # ### end Alembic commands ###
