"""Add is_admin flag to User model

Revision ID: 353e7fba1d6f
Revises: 
Create Date: 2025-07-20 09:36:52.906302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353e7fba1d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Comment out table creation since tables already exist in production
    # op.create_table('anonymous_usage',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('session_id', sa.String(length=64), nullable=False),
    # sa.Column('ip_address', sa.String(length=45), nullable=True),
    # sa.Column('conversions_today', sa.Integer(), nullable=True),
    # sa.Column('last_conversion', sa.DateTime(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('anonymous_usage', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_anonymous_usage_session_id'), ['session_id'], unique=False)

    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=120), nullable=False),
    # sa.Column('password_hash', sa.String(length=128), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.Column('is_premium', sa.Boolean(), nullable=True),
    # sa.Column('is_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    # sa.Column('premium_expires', sa.DateTime(), nullable=True),
    # sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    # sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('stripe_customer_id'),
    # sa.UniqueConstraint('stripe_subscription_id')
    # )
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # op.create_table('conversions',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('session_id', sa.String(length=64), nullable=True),
    # sa.Column('original_filename', sa.String(length=255), nullable=False),
    # sa.Column('file_size', sa.Integer(), nullable=True),
    # sa.Column('file_type', sa.String(length=10), nullable=True),
    # sa.Column('conversion_type', sa.String(length=20), nullable=True),
    # sa.Column('status', sa.String(length=20), nullable=True),
    # sa.Column('error_message', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('completed_at', sa.DateTime(), nullable=True),
    # sa.Column('processing_time', sa.Float(), nullable=True),
    # sa.Column('markdown_length', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    
    # Only add the is_admin column to existing users table
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the is_admin column from users table
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
