"""add_api_key_to_user

Revision ID: 356d23396c69
Revises: 86ef39e350ee
Create Date: 2025-07-21 09:43:09.663184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356d23396c69'
down_revision = '86ef39e350ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
