"""add_api_key_to_user

Revision ID: 356d23396c69
Revises: 86ef39e350ee
Create Date: 2025-07-21 09:43:09.663184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356d23396c69'
down_revision = '86ef39e350ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if api_key column already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'api_key' not in columns:
        # Add api_key column to users table
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        print("✅ Added api_key column to users table")
    else:
        print("ℹ️  api_key column already exists, skipping...")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
