"""Add job_id column to existing conversions table

Revision ID: 86ef39e350ee
Revises: 4dfacf4ae44f
Create Date: 2025-07-20 19:58:04.134285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ef39e350ee'
down_revision = '4dfacf4ae44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
    
    # Add job_id column to conversions table (idempotent)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('conversions')]
    
    if 'job_id' not in columns:
        with op.batch_alter_table('conversions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('job_id', sa.String(length=64), nullable=True))
        print("✅ Added job_id column to conversions table")
    else:
        print("ℹ️  job_id column already exists, skipping...")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    
    # Remove job_id column from conversions table
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_column('job_id')
    # ### end Alembic commands ###
