"""Add structured_data column to Conversion model

Revision ID: 8ddbcc4fa19d
Revises: 5af2674b0a9e
Create Date: 2025-07-31 14:08:42.797986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddbcc4fa19d'
down_revision = '5af2674b0a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_column('structured_data')

    # ### end Alembic commands ###
