"""Add structured_data column to Conversion model

Revision ID: 8ddbcc4fa19d
Revises: 5af2674b0a9e
Create Date: 2025-07-31 14:08:42.797986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8ddbcc4fa19d'
down_revision = '5af2674b0a9e'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('conversions', 'structured_data'):
        with op.batch_alter_table('conversions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('conversions', 'structured_data'):
        with op.batch_alter_table('conversions', schema=None) as batch_op:
            batch_op.drop_column('structured_data')
    # ### end Alembic commands ###
