"""Add missing subscription columns to users table

Revision ID: add_missing_subscription_columns
Revises: 6be108e3005a
Create Date: 2025-07-27 21:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_missing_subscription_columns'
down_revision = '6be108e3005a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add subscription management fields
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True, server_default='trial'))
        batch_op.add_column(sa.Column('current_tier', sa.String(length=50), nullable=True, server_default='free'))
        batch_op.add_column(sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('subscription_start_date')
        batch_op.drop_column('current_tier')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ### 